#!/bin/bash

/usr/sbin/sendmail -t <<ERRMAIL
To: $1
From: systemd@$HOSTNAME <root@$HOSTNAME>
Subject: $2
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8

$(systemctl status --full "$2")
ERRMAIL
